5.4 checksums

diff --git a/main/linux-rpi/APKBUILD b/main/linux-rpi/APKBUILD
--- a/main/linux-rpi/APKBUILD
+++ b/main/linux-rpi/APKBUILD
@@ -50,34 +50,34 @@ HOSTCC="${CC:-gcc}"
 HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
 
 prepare() {
-	# local _patch_failed=
-	# cd "$srcdir"/linux-$_kernver
-	# if [ "${pkgver%.0}" = "$pkgver" ]; then
-	# 	msg "Applying patch-$pkgver.xz"
-	# 	unxz -c < "$srcdir"/patch-$pkgver.xz | patch -p1 -N
-	# fi
+	local _patch_failed=
+	cd "$srcdir"/linux-$_kernver
+	if [ "${pkgver%.0}" = "$pkgver" ]; then
+		msg "Applying patch-$pkgver.xz"
+		unxz -c < "$srcdir"/patch-$pkgver.xz | patch -p1 -N
+	fi
 
-	# # first apply patches in specified order
-	# for i in $source; do
-	# 	case $i in
-	# 	*.patch)
-	# 		msg "Applying $i..."
-	# 		if ! patch -s -p1 -N -i "$srcdir"/${i##*/}; then
-	# 			echo $i >>failed
-	# 			_patch_failed=1
-	# 		fi
-	# 		;;
-	# 	esac
-	# done
+	# first apply patches in specified order
+	for i in $source; do
+		case $i in
+		*.patch)
+			msg "Applying $i..."
+			if ! patch -s -p1 -N -i "$srcdir"/${i##*/}; then
+				echo $i >>failed
+				_patch_failed=1
+			fi
+			;;
+		esac
+	done
 
-	# if ! [ -z "$_patch_failed" ]; then
-	# 	error "The following patches failed:"
-	# 	cat failed
-	# 	return 1
-	# fi
+	if ! [ -z "$_patch_failed" ]; then
+		error "The following patches failed:"
+		cat failed
+		return 1
+	fi
 
-	# # remove localversion from patch if any
-	# rm -f localversion*
+	# remove localversion from patch if any
+	rm -f localversion*
 
 	local flavor=
 	for flavor in $_flavors; do
@@ -102,7 +102,7 @@ _genconfig() {
 	local builddir="$srcdir"/build-$flavor
 	local defconfig=
 	case $flavor in
-		rpi) defconfig=bcmrpi_defconfig
+		rpi) defconfig=bcmrpi_defconfig ;;
 		rpi2) defconfig=bcm2709_defconfig ;;
     rpi3) defconfig=bcm2708_defconfig ;;
 		rpi4) defconfig=bcm2711_defconfig ;;
@@ -289,3 +289,10 @@ _dev() {
 		"$subpkgdir"/lib/modules/${_abi_release}/build
 }
 
+sha512sums="05b146e1e01b514b25617fbe90853c388dda355e5842878acc209999dd64e6465de7149c00d2d2af4589c6aa27d95d6ec0d9c3e5dcd582c09f098d9fab57739a  linux-5.4-rc8.tar.gz
+6c1c1c61ceb323eecb0e81e226af6b5b8fef7c8c075b1eb836639f465de5ef5d23648716c953d295250f8c6567546782956afe644573b84920a4f6902a1a0454  config-changes-rpi.armhf
+6c1c1c61ceb323eecb0e81e226af6b5b8fef7c8c075b1eb836639f465de5ef5d23648716c953d295250f8c6567546782956afe644573b84920a4f6902a1a0454  config-changes-rpi2.armhf
+6c1c1c61ceb323eecb0e81e226af6b5b8fef7c8c075b1eb836639f465de5ef5d23648716c953d295250f8c6567546782956afe644573b84920a4f6902a1a0454  config-changes-rpi3.armv7
+6c1c1c61ceb323eecb0e81e226af6b5b8fef7c8c075b1eb836639f465de5ef5d23648716c953d295250f8c6567546782956afe644573b84920a4f6902a1a0454  config-changes-rpi4.armv7
+6c1c1c61ceb323eecb0e81e226af6b5b8fef7c8c075b1eb836639f465de5ef5d23648716c953d295250f8c6567546782956afe644573b84920a4f6902a1a0454  config-changes-rpi3.aarch64
+6c1c1c61ceb323eecb0e81e226af6b5b8fef7c8c075b1eb836639f465de5ef5d23648716c953d295250f8c6567546782956afe644573b84920a4f6902a1a0454  config-changes-rpi4.aarch64"
